version: '3.1'

services:
  db:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_DB: articlehub
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: docker
    ports:
      - "5432:5432"
    volumes:
      - article-db-data:/var/lib/postgresql

volumes:
  article-db-data: